### ISSUE TITLE
"simulation/matlab/gpd2" not found

### ISSUE THREAD

**Issue by Fang-Haoshu** [mgualti/PickAndPlace#1]
Hi there! Thanks a lot for your sharing！ The code will help a lot to our research!
A small problem I met is that, I could not found the dir "simulation/matlab/gpd2" mentioned in the readme. Do I just miss anything?

**Comment by mgualti** [comment]
Oops, sorry about that -- gpd2 was excluded by the gitignore list. It's been added now.

**Comment by Fang-Haoshu** [comment]
Thanks!
